enable-magisk-update = false   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = false
build-mode = "apk"
excluded-patches = ""
included-patches = ""
version = "auto"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[YouTube-ReX]
app-name = "YouTube"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReX"
build-mode = "both"
excluded-patches = "'Custom branding heading' 'Custom branding icon YouTube' 'Custom branding name YouTube'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
enabled = false
build-mode = "apk"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Music-ReX]
app-name = "Music"
patches-source = "YT-Advanced/ReX-patches"
integrations-source = "YT-Advanced/ReX-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReX"
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Twitter]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[Twitch]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[TikTok]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"

[Reddit]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"

[YouTube-Extended]
enabled = false
app-name = "YouTube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Premium heading'"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"

[Reddit-Extended]
enabled = false
app-name = "Reddit"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced Extended"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.reddit.frontpage"
